name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**/*.txt', '**/*.md']
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/*.txt', '**/*.md']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*', 20]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install
      - run: yarn test
      - run: yarn build
